version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: archives-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    networks:
      airflow_network:
        ipv4_address: 172.20.0.2

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      airflow_network:
        ipv4_address: 172.20.0.3
    depends_on:
      - postgres

  airflow:
    image: apache/airflow:2.10.5-python3.10
    container_name: archives-airflow
    command: webserver
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__STORE_DAG_CODE: "True"
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "airflow webserver --help"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      airflow_network:
        ipv4_address: 172.20.0.4

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: airflow
      MB_DB_PORT: 5432
      MB_DB_USER: airflow
      MB_DB_PASS: airflow
      MB_DB_HOST: postgres
    depends_on:
      - postgres
    networks:
      airflow_network:
        ipv4_address: 172.20.0.5

networks:
  airflow_network:
    ipam:
      config:
        - subnet: 172.20.0.0/24